# Generated by Django 4.2.1 on 2023-07-10 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topstudents',
            name='grade',
            field=models.SmallIntegerField(choices=[(0, 'دهم'), (1, 'یازدهم'), (2, 'داوزدهم')], max_length=1, verbose_name='پایه تحصیلی'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='وضعیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
